# Generated by Django 5.1 on 2024-09-11 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_height_products_length_products_main_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='height',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='basket',
            name='length',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='basket',
            name='main_foto',
            field=models.ImageField(blank=True, null=True, upload_to='main_product_images'),
        ),
        migrations.AddField(
            model_name='basket',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='basket',
            name='product_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='width',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
