# Generated by Django 5.1 on 2024-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_favouriteproduct_category_favouriteproduct_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
