# Generated by Django 5.1 on 2024-09-21 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_mini',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media/mini_product_images/'),
            preserve_default=False,
        ),
    ]
