# Generated by Django 5.1 on 2024-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productimage_image_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_mini',
            field=models.ImageField(blank=True, null=True, upload_to='media/mini_product_images/'),
        ),
    ]
