# Generated by Django 5.1 on 2024-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productimage_image_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_mini',
            field=models.ImageField(blank=True, null=True, upload_to='mini_product_images/'),
        ),
    ]
