# Generated by Django 5.1 on 2024-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteproduct',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
