# Generated by Django 5.1 on 2024-09-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_favouriteproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproduct',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
