# Generated by Django 5.1 on 2024-09-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_favouriteproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouriteproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
