# Generated by Django 5.1 on 2024-09-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_favouriteproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favouriteproduct',
            name='status',
        ),
    ]
